
services:         
  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demodb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
       - mariadb:/var/lib/mysql
volumes:
  mariadb: